import express from "express";
import authRoutes from "./auth.routes.js";
import categoryRoutes from "./category.routes.js";
import productRoutes from "./product.routes.js";
import seoRoutes from "./seo.routes.js";
import wishlistRoutes from "./wishlist.routes.js";
import cartItemRoutes from "./cartItem.routes.js";
import cartRoutes from "./cart.routes.js";
import orderRoutes from "./order.routes.js";
import paymentRoutes from "./payment.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import userRoutes from "./user.routes.js";
import sellerRoutes from "./seller.routes.js";
import reviewRoutes from "./review.routes.js";
import recommendationRoutes from "./revommendation.routes.js";
const router = express.Router();

router.use("/auth", authRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/products", seoRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/cart", cartRoutes);
router.use("/cart", cartItemRoutes);
router.use("/orders", orderRoutes);
router.use("/payments", paymentRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/users", userRoutes);
router.use("/sellers", sellerRoutes);
router.use("/reviews", reviewRoutes);
router.use("/products", recommendationRoutes);

export default router;
